---
- name: Deploy App to Remote Server
  hosts: all
  tasks:
    - name: Copy files to remote server
      copy:
        src: /home/runner/work/shellscript/shellscript/
        dest: /home/mounica1/shellscript
      become: yes
