---
- name: Deploy App to Remote Server
  hosts: all
  environment:
    CSR_countryName: "US"
    CSR_stateOrProvinceName: "Michigan"
    CSR_localityName: "Troy"
    CSR_organizationalUnitName: "Vehma International"
    CSR_commonName: "cse-plant1-uns.magna.global"
  tasks:
    - name: Copy files to remote server
      copy:
        src: /home/runner/work/shellscript/shellscript/
        dest: /home/mounica1/shellscript
      become: yes
    
    - name: Generate certificate
      shell: |
        echo "Cert creation starts"
        openssl req \
        -nodes \
        -newkey rsa:2048 \
        -subj "/C=$CSR_countryName/ST=$CSR_stateOrProvinceName/L=$CSR_localityName/O=Magna International/OU=$CSR_organizationalUnitName/CN=$CSR_commonName" \
        -addext "keyUsage = digitalSignature, keyEncipherment" \
        -addext "extendedKeyUsage = serverAuth, clientAuth" \
        -addext "subjectAltName = DNS:$CSR_commonName" \
        -keyout $CSR_commonName.key \
        -out $CSR_commonName.csr
        echo "::$CSR_commonName.key got created"
        echo "::$CSR_commonName.csr got created"
        echo "pwd"
        pwd
        ls -lrt
        echo "ls -lrt"
        echo "Cert creation ends"
      args:
        executable: /bin/bash
        
   - name: Create folder certs
      command: >
        sudo mkdir -p /home/mounica1/certs &&
        sudo cp -R /home/mounica1{{ CSR_commonName }}.key /home/mounica1/certs/
      args:
        executable: /bin/bash
