name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to Remote Server
        run: |
          sshpass -p 'Pol9star@' ssh -o StrictHostKeyChecking=no mounica1@ec2-52-90-61-203.compute-1.amazonaws.com 'bash -s' < shell.sh
