name: CI 

on: [push]  # You can customize the trigger event(s) here

jobs:
  install-docker:
    runs-on: ubuntu-latest  # You can choose a different OS if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          # Install Docker using the official installation script
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER  # Add your user to the docker group
          docker version  # Verify Docker installation

      - name: Clean Up
        run: rm get-docker.sh

      - name: Run script file
        run: |
           chmod +x ./test.sh
           ./test.sh
        shell: bash
